Initial commit
auvaraksin/JAVA-ENVIRONMENT-COURSEWORK pull request #1
Opened 2022-05-15 23:21 UTC by auvaraksin

2022-05-16 16:25 UTC, OlgaLugacheva requested changes

2022-05-16 16:25 UTC, OlgaLugacheva commented on src/test/java/pro/sky/javaenvironmentcoursework/services/ExaminerServiceImplTest.java
> +        Assertions.assertEquals(DEFAULT_QUESTION_RANDOMLIST, out.getQuestions(anyInt()));
как бы мог выглядеть именно этот тест: 

```
    @Test
    public void shouldReturnAnyListWhenCallGetQuestionsMethod() {
        Collection<Question> questionList = List.of(new Question("quest", "answer"));
        when(questionsRepositoryMock.getAll()).thenReturn(questionList);
        when(questionsRepositoryMock.getRandomQuestion()).thenReturn(new Question("quest", "answer"));
        Assertions.assertEquals(questionList, out.getQuestions(1));
    }
```

2022-05-16 16:25 UTC, OlgaLugacheva commented on src/test/java/pro/sky/javaenvironmentcoursework/services/ExaminerServiceImplTest.java
> +import pro.sky.javaenvironmentcoursework.services.implementations.ExaminerServiceImpl;
не нашла такого класса в проекте

2022-05-16 19:54 UTC, auvaraksin commented on src/test/java/pro/sky/javaenvironmentcoursework/services/ExaminerServiceImplTest.java
> +import pro.sky.javaenvironmentcoursework.services.implementations.ExaminerServiceImpl;
Исправлено, подгружено.

2022-05-17 05:49 UTC, OlgaLugacheva approved these changes

2022-05-30 20:09 UTC, merged